### PR TITLE
added SASS/SCSS support. Not longer ignore .scss files.

### PR DESCRIPTION
**Pull request by aligo**

### CODE REVIEW

**Comment by rromanchuk** [comment]
+1

**Comment by fabiomcosta** [comment]
Currently, .scss files are not being matched, which should be fixed. I have no idea if this patch fixes it.

**Comment by regedarek** [comment]
+1

**Comment by djspinmonkey** [comment]
I just spent many hours looking for a bug instead of finding it in the first few minutes, because I assumed ack searched .scss files.  I'm not angry -- ack is awesome! -- but it would be great to prevent that from happening to others in the future.  +1 to this feature request.

**Comment by petdance** [comment]
ack 2.0 will search all text files by default.  This won't change in 1.x

http://github.com/petdance/ack2

**Comment by petdance** [comment]
Handy tip for figuring what ack is searching: Run ack with the `-f` flag.

**Pull request closed without merging**
