### PR TITLE
CoffeeScript support

### PR DESCRIPTION
**Pull request by jannehietamaki**
Added coffeescript support

### CODE REVIEW

**Comment by petdance** [comment]
"Disclaimer: CoffeeScript is just for fun."  I'm going to decline this one.  Thanks.

**Comment by jannehietamaki** [comment]
Programming should be fun.

CoffeeScript is ranked as one of the most interesting projects in GitHub https://github.com/repositories . There's a lot of people who are taking it seriously, and the next version of Rails (3.1) will support it natively.

http://en.wikipedia.org/wiki/CoffeeScript

**Comment by bts** [comment]
Coffeescript's really gaining a lot of traction; I ask that you please reconsider supporting it. I know personally that any (would-be) javascript I will be writing for future projects is all going to be coffeescript going forward. And at least within the ruby community I know I'm not alone. It would be a shame to have to maintain a personal fork  or point to another non-canonical fork of ack to have support for this up-and-coming language.

**Comment by petdance** [comment]
Are you on the ack-users mailing list?  I'm guessing not.  Please sign up, and then read the last few days about where I'm standing on adding new filetypes, and working at starting ack 2.0.  I would love to have help on it, planning for the future where all future filetypes can be dealt with.

**Pull request closed without merging**
